version: "3.9"

services:

  # Portainer - WebUI for Containers
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    networks:
      - default
    command: -H unix:///var/run/docker.sock 
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro 
      - D:/Docker/portainer/data:/data 
    environment:
      - TZ="America/New_York"

networks:
  default:
    driver: bridge